
CREATE SCHEMA Sales;

CREATE TABLE Sales.AllSales (OrderName NVARCHAR (50),
							 OrderId NVARCHAR (50),
							 InvoiceId NVARCHAR (50),
							 CustomerName NVARCHAR (50),
							 InvStatus NVARCHAR (50),
							 Fulfillment NVARCHAR (50),
							 Method1 NVARCHAR (50),
							 Method2 NVARCHAR (50),
							 Method3 NVARCHAR (50),
							 Method4 NVARCHAR (50),
							 PaySource NVARCHAR (50),
							 Store NVARCHAR (50),
							 CreateDate DATE,
							 PayDate DATE,
							 FulfillDate DATE,
							 CancelDate DATE,
							 CustomerId NVARCHAR (50),
							 Phone NVARCHAR (50),
							 Email NVARCHAR (50),
							 Item NVARCHAR (MAX),
							 Vendor NVARCHAR (50),
							 SKU NVARCHAR (MAX),
							 New_Item NVARCHAR (MAX),
							 Shipped INT,
							 DwUnitPrice NVARCHAR (50),
							 Ordered INT,
							 UpUnitPrice NVARCHAR (50),
							 BillingName NVARCHAR (50),
							 BillingStreet NVARCHAR (MAX),
							 BillingCity NVARCHAR (50),
							 BillingProvince NVARCHAR (50),
							 BillingZip INT,
							 ShippingName NVARCHAR (50),
							 ShippingStreet NVARCHAR (MAX),
							 ShippingCity NVARCHAR (50),
							 ShippingProvince NVARCHAR (50),
							 ShippingZip INT,
							 ShippingMethod NVARCHAR (50),
							 TaxManassas NVARCHAR (50),
							 TaxVirginia NVARCHAR (50),
							 TaxGoogle NVARCHAR (50),
							 TaxNebraska NVARCHAR (50),
							 TaxTennessee NVARCHAR (50),
							 TaxNevada NVARCHAR (50),
							 TaxNewYork NVARCHAR (50),
							 TaxOther NVARCHAR (50),
							 TaxTotal NVARCHAR (50),
							 Subtotal NVARCHAR (50),
							 Discount NVARCHAR (50),
							 Shipping NVARCHAR (50),
							 TotalExcTax NVARCHAR (50),
							 InvoiceTotal NVARCHAR (50),
							 PaidTotal NVARCHAR (50),
							 AmountDue NVARCHAR (50),
							 Refund NVARCHAR (50));


select *
from Sales.AllSales

TRUNCATE TABLE Sales.AllSales